[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
plotarmor = "HSU9d7nCkGNWmBSCmwWpTHBZCHiNFhwFC4e9M2jWFFCm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
