[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
plotarmor = "D956znqaTD6P7UW4LL6VQN7FNQqeFdszAsM7cmABJGUA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
